package cn.contract.ota.ctrip.ari;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-29T15:17:44.039+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "HotelRateAmountNotif", 
                  wsdlLocation = "https://vendor.ctrip.com/Hotel/OTAReceive/HotelRateAmountNotif.asmx?wsdl",
                  targetNamespace = "http://www.opentravel.org/OTA/2003/05") 
public class HotelRateAmountNotif extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.opentravel.org/OTA/2003/05", "HotelRateAmountNotif");
    public final static QName HotelRateAmountNotifSoap12 = new QName("http://www.opentravel.org/OTA/2003/05", "HotelRateAmountNotifSoap12");
    public final static QName HotelRateAmountNotifSoap = new QName("http://www.opentravel.org/OTA/2003/05", "HotelRateAmountNotifSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://vendor.ctrip.com/Hotel/OTAReceive/HotelRateAmountNotif.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelRateAmountNotif.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://vendor.ctrip.com/Hotel/OTAReceive/HotelRateAmountNotif.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelRateAmountNotif(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelRateAmountNotif(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelRateAmountNotif() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HotelRateAmountNotif(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HotelRateAmountNotif(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HotelRateAmountNotif(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HotelRateAmountNotifSoap
     */
    @WebEndpoint(name = "HotelRateAmountNotifSoap12")
    public HotelRateAmountNotifSoap getHotelRateAmountNotifSoap12() {
        return super.getPort(HotelRateAmountNotifSoap12, HotelRateAmountNotifSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelRateAmountNotifSoap
     */
    @WebEndpoint(name = "HotelRateAmountNotifSoap12")
    public HotelRateAmountNotifSoap getHotelRateAmountNotifSoap12(WebServiceFeature... features) {
        return super.getPort(HotelRateAmountNotifSoap12, HotelRateAmountNotifSoap.class, features);
    }


    /**
     *
     * @return
     *     returns HotelRateAmountNotifSoap
     */
    @WebEndpoint(name = "HotelRateAmountNotifSoap")
    public HotelRateAmountNotifSoap getHotelRateAmountNotifSoap() {
        return super.getPort(HotelRateAmountNotifSoap, HotelRateAmountNotifSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelRateAmountNotifSoap
     */
    @WebEndpoint(name = "HotelRateAmountNotifSoap")
    public HotelRateAmountNotifSoap getHotelRateAmountNotifSoap(WebServiceFeature... features) {
        return super.getPort(HotelRateAmountNotifSoap, HotelRateAmountNotifSoap.class, features);
    }

}
