package cn.contract.ota.ctrip.ari;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-29T15:16:56.587+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.opentravel.org/OTA/2003/05", name = "HotelAvailNotifSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HotelAvailNotifSoap {

    @WebResult(name = "OTA_HotelAvailNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "RequestResult")
    @WebMethod(operationName = "Request", action = "http://www.opentravel.org/OTA/2003/05/Request")
    public OTAHotelAvailNotifRS request(
            @WebParam(partName = "request", name = "OTA_HotelAvailNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
            OTAHotelAvailNotifRQ request
    );
}
