
package cn.contract.ota.ctrip.ari;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-06T11:05:48.842+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class OTAReceiveServiceSoap_OTAReceiveServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.opentravel.org/OTA/2003/05", "OTAReceiveService");

    private OTAReceiveServiceSoap_OTAReceiveServiceSoap12_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = OTAReceiveService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OTAReceiveService ss = new OTAReceiveService(wsdlURL, SERVICE_NAME);
        OTAReceiveServiceSoap port = ss.getOTAReceiveServiceSoap12();  
        
        {
        System.out.println("Invoking hotelInvCountNotif...");
        cn.contract.ota.ctrip.ari.OTAHotelInvCountNotifRQ _hotelInvCountNotif_request = null;
        cn.contract.ota.ctrip.ari.OTAHotelInvCountNotifRS _hotelInvCountNotif__return = port.hotelInvCountNotif(_hotelInvCountNotif_request);
        System.out.println("hotelInvCountNotif.result=" + _hotelInvCountNotif__return);


        }
        {
        System.out.println("Invoking hotelAvailNotif...");
        cn.contract.ota.ctrip.ari.OTAHotelAvailNotifRQ _hotelAvailNotif_request = null;
        cn.contract.ota.ctrip.ari.OTAHotelAvailNotifRS _hotelAvailNotif__return = port.hotelAvailNotif(_hotelAvailNotif_request);
        System.out.println("hotelAvailNotif.result=" + _hotelAvailNotif__return);


        }
        {
        System.out.println("Invoking hotelCheckOutNotif...");
        cn.contract.ota.ctrip.ari.OTAHotelResCheckOutNotifRQ _hotelCheckOutNotif_request = null;
        cn.contract.ota.ctrip.ari.OTAHotelResCheckOutNotifRS _hotelCheckOutNotif__return = port.hotelCheckOutNotif(_hotelCheckOutNotif_request);
        System.out.println("hotelCheckOutNotif.result=" + _hotelCheckOutNotif__return);


        }
        {
        System.out.println("Invoking hotelRateAmountNotif...");
        cn.contract.ota.ctrip.ari.OTAHotelRateAmountNotifRQ _hotelRateAmountNotif_request = null;
        cn.contract.ota.ctrip.ari.OTAHotelRateAmountNotifRS _hotelRateAmountNotif__return = port.hotelRateAmountNotif(_hotelRateAmountNotif_request);
        System.out.println("hotelRateAmountNotif.result=" + _hotelRateAmountNotif__return);


        }
        {
        System.out.println("Invoking hotelCheckInNotif...");
        cn.contract.ota.ctrip.ari.OTAHotelResCheckInNotifRQ _hotelCheckInNotif_request = null;
        cn.contract.ota.ctrip.ari.OTAHotelResCheckInNotifRS _hotelCheckInNotif__return = port.hotelCheckInNotif(_hotelCheckInNotif_request);
        System.out.println("hotelCheckInNotif.result=" + _hotelCheckInNotif__return);


        }
        {
        System.out.println("Invoking notifReport...");
        cn.contract.ota.ctrip.ari.OTANotifReportRQ _notifReport_request = null;
        cn.contract.ota.ctrip.ari.OTANotifReportRS _notifReport__return = port.notifReport(_notifReport_request);
        System.out.println("notifReport.result=" + _notifReport__return);


        }
        {
        System.out.println("Invoking hotelRatePlan...");
        cn.contract.ota.ctrip.ari.OTAHotelRatePlanRQ _hotelRatePlan_request = null;
        cn.contract.ota.ctrip.ari.OTAHotelRatePlanRS _hotelRatePlan__return = port.hotelRatePlan(_hotelRatePlan_request);
        System.out.println("hotelRatePlan.result=" + _hotelRatePlan__return);


        }

        System.exit(0);
    }

}
